In [3]:
import numpy as np
arr= np.array([1,2,3,4,5])
type(arr)

numpy.ndarray

In [5]:
import numpy as np
arr=np.array((1,2,3,4,5))
print(arr)
type(arr)

[1 2 3 4 5]


numpy.ndarray

# 2D Array

In [6]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
arr[1,2]

6

In [8]:
arr[0][1]

2

In [9]:
for x in arr:
    print(x)

[1 2 3]
[4 5 6]
[7 8 9]


# 3D Array

In [12]:
import numpy as np
arr=np.array([[[1,2,3],[4,5,6]],[[6,7,8],[9,10,11]],[[12,13,14],[15,16,17]]])
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17]]])

In [13]:
arr[0,1,2]

6

In [14]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-1])

[5 6]


In [16]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])

[2 4]


In [1]:
mylist=[1,2,3,4,5]
print(mylist)

[1, 2, 3, 4, 5]


In [2]:
type(mylist)

list

In [3]:
import numpy as np
arr=np.array(mylist)
arr

array([1, 2, 3, 4, 5])

In [4]:
type(arr)

numpy.ndarray

In [5]:
arr.shape

(5,)

In [12]:
mylist1=[1,2,3,4,5]
mylist2=[2,3,4,5,6]
mylist3=[3,4,5,6,7]
arr=np.array([mylist1,mylist2,mylist3])
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [13]:
arr.shape

(3, 5)

In [14]:
arr.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 5],
       [6, 3, 4],
       [5, 6, 7]])

In [15]:
arr=np.array([mylist1,mylist2,mylist3])
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [16]:
arr[:,:]

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [17]:
arr[0:2,0:2]

array([[1, 2],
       [2, 3]])

In [18]:
arr[1:3,3:5]

array([[5, 6],
       [6, 7]])

In [19]:
arr[:3]

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [20]:
arr[1:,3:]

array([[5, 6],
       [6, 7]])

In [21]:
arr[1:,1:4]

array([[3, 4, 5],
       [4, 5, 6]])

In [22]:
arr[1,1:4]

array([3, 4, 5])

In [23]:
arr=np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
arr[3:]=100
arr

array([  0,   1,   2, 100, 100, 100, 100, 100, 100, 100])

In [30]:
arr=np.arange(0,20,step=2)
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [28]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [31]:
arr1=arr
arr1

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [32]:
arr1[4:]=100
arr1

array([  0,   2,   4,   6, 100, 100, 100, 100, 100, 100])

In [33]:
arr

array([  0,   2,   4,   6, 100, 100, 100, 100, 100, 100])

In [34]:
arr1=arr.copy()
arr1

array([  0,   2,   4,   6, 100, 100, 100, 100, 100, 100])

In [35]:
arr1[4:]=500
arr1

array([  0,   2,   4,   6, 500, 500, 500, 500, 500, 500])

In [36]:
arr

array([  0,   2,   4,   6, 100, 100, 100, 100, 100, 100])

In [37]:
arr2=arr.copy()
arr2

array([  0,   2,   4,   6, 100, 100, 100, 100, 100, 100])

In [38]:
arr[3:]=10
arr

array([ 0,  2,  4, 10, 10, 10, 10, 10, 10, 10])

In [39]:
arr2

array([  0,   2,   4,   6, 100, 100, 100, 100, 100, 100])

In [40]:
arr2[arr2<100]

array([0, 2, 4, 6])

In [41]:
arr2[arr2<150]

array([  0,   2,   4,   6, 100, 100, 100, 100, 100, 100])

In [44]:
arr2[arr2<2]

array([0])

In [48]:
np.ones(5,dtype=int)

array([1, 1, 1, 1, 1])

In [50]:
np.ones((2,2),dtype=int)

array([[1, 1],
       [1, 1]])

In [51]:
np.random.rand(3,3)

array([[0.29212626, 0.88148802, 0.43567066],
       [0.87058994, 0.63575538, 0.08624699],
       [0.71459482, 0.65726346, 0.43026647]])

In [63]:
np.random.randint(0,100,4).reshape(2,2)

array([[81,  4],
       [98, 29]])

In [64]:
np.random.random_sample((1,10))

array([[0.42971716, 0.44283645, 0.77617156, 0.24302098, 0.55253441,
        0.91034954, 0.54702093, 0.91386221, 0.94376001, 0.35892512]])

In [2]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[::2])

[1 3 5 7]


In [6]:
print(arr[1:5])

[2 3 4 5]


In [10]:
arr1=np.arange(1,10).reshape(3,3)
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
arr2=np.arange(1,19,step=2).reshape(3,3)
arr2

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

In [14]:
#addition of two array

In [15]:
arr1+arr2

array([[ 2,  5,  8],
       [11, 14, 17],
       [20, 23, 26]])

In [16]:
np.add(arr1,arr2)

array([[ 2,  5,  8],
       [11, 14, 17],
       [20, 23, 26]])

In [17]:
#substraction of two array 

In [18]:
arr1-arr2

array([[ 0, -1, -2],
       [-3, -4, -5],
       [-6, -7, -8]])

In [20]:
np.subtract(arr1,arr2)

array([[ 0, -1, -2],
       [-3, -4, -5],
       [-6, -7, -8]])

In [21]:
#divide one array by another array

In [22]:
np.divide(arr1,arr2)

array([[1.        , 0.66666667, 0.6       ],
       [0.57142857, 0.55555556, 0.54545455],
       [0.53846154, 0.53333333, 0.52941176]])

In [23]:
arr1/arr2

array([[1.        , 0.66666667, 0.6       ],
       [0.57142857, 0.55555556, 0.54545455],
       [0.53846154, 0.53333333, 0.52941176]])

In [24]:
#multiplication of two array

In [25]:
arr1*arr2

array([[  1,   6,  15],
       [ 28,  45,  66],
       [ 91, 120, 153]])

In [26]:
#multiplication of two matrix

In [27]:
arr1 @ arr2

array([[ 54,  66,  78],
       [117, 147, 177],
       [180, 228, 276]])

In [28]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
#finding maximum element in array

In [29]:
arr1.max()

9

In [ ]:
#finding imdex of maximum  element in array 

In [30]:
arr1.argmax()

8

In [ ]:
#finding minimum number in each column

In [31]:
arr1.max(axis=0)

array([7, 8, 9])

In [ ]:
#finding maximum number in each row 

In [32]:
arr1.max(axis=1)

array([3, 6, 9])

In [ ]:
#finding mimimum element in array

In [33]:
arr1.min()

1

In [ ]:
#finding index of mimimum element in array

In [34]:
arr1.argmin()

0

In [ ]:
#finding minimum number in each row 

In [35]:
arr1.min(axis=1)

array([1, 4, 7])

In [ ]:
#finding minimum number in  each column 

In [36]:
arr1.min(axis=0)

array([1, 2, 3])

In [37]:
np.sum(arr1)

45

In [ ]:
#finding sum of each column 

In [38]:
np.sum(arr1,axis=0)

array([12, 15, 18])

In [39]:
#finding sum of each row 

In [40]:
np.sum(arr1,axis=1)

array([ 6, 15, 24])

In [41]:
#finding mean of the array 

In [42]:
np.mean(arr1)

5.0

In [ ]:
#finding square root of each element in array 

In [44]:
np.sqrt(arr1)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [45]:
#finding standard deviation of matrix or array

In [46]:
np.std(arr1)

2.581988897471611

In [47]:
#finding exponent of each element of array 

In [48]:
np.exp(arr1)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

In [49]:
#finding log of each element of array

In [50]:
np.log(arr1)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

# multiplication of two matrix we can use dot function

In [52]:
arr1.dot(arr2)

array([[ 54,  66,  78],
       [117, 147, 177],
       [180, 228, 276]])

# python Numpy Array slicing

In [53]:
import numpy as np

In [54]:
 mx=np.arange(1,101).reshape(10,10)
mx

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [56]:
mx[0,0]

1

In [57]:
mx[1].ndim

1

In [59]:
mx[:,0]

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [60]:
mx[:,0:1]

array([[ 1],
       [11],
       [21],
       [31],
       [41],
       [51],
       [61],
       [71],
       [81],
       [91]])

In [61]:
mx[1:4,1:4]

array([[12, 13, 14],
       [22, 23, 24],
       [32, 33, 34]])

In [62]:
mx[:]

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [63]:
mx[::]

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [ ]:
#what is the size required to store the array in byte

In [64]:
mx.itemsize

4

In [65]:
mx.dtype

dtype('int32')

# python numpy concatenation and spliting

In [66]:
import numpy as np

In [69]:
arr1=np.arange(1,17).reshape(4,4)
arr2=np.arange(17,33).reshape(4,4)
print(arr1)
print(arr2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]]


In [70]:
np.concatenate((arr1,arr2))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [71]:
np.concatenate((arr1,arr2),axis=1)

array([[ 1,  2,  3,  4, 17, 18, 19, 20],
       [ 5,  6,  7,  8, 21, 22, 23, 24],
       [ 9, 10, 11, 12, 25, 26, 27, 28],
       [13, 14, 15, 16, 29, 30, 31, 32]])

In [72]:
np.vstack((arr1,arr2))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [73]:
np.hstack((arr1,arr2))

array([[ 1,  2,  3,  4, 17, 18, 19, 20],
       [ 5,  6,  7,  8, 21, 22, 23, 24],
       [ 9, 10, 11, 12, 25, 26, 27, 28],
       [13, 14, 15, 16, 29, 30, 31, 32]])

In [74]:
np.split(arr1,2)

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]])]

In [75]:
np.split(arr1,2,axis=1)#spliting  array rowwise

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16]])]

In [76]:
arr1=np.array([1,2,3,4,5,6])

In [77]:
np.split(arr1,[2])#spliting array from second index

[array([1, 2]), array([3, 4, 5, 6])]

In [78]:
np.split(arr1,[1,3])

[array([1]), array([2, 3]), array([4, 5, 6])]

In [79]:
#random sampling with numpy

In [80]:
np.random.random((3,3))#returns 3*3 array of random numbersnp

array([[0.76074735, 0.92407823, 0.10097894],
       [0.8646574 , 0.79538822, 0.50774516],
       [0.76656288, 0.83211668, 0.37436259]])

In [83]:
np.random.randint((3,3))

array([1, 1])

In [86]:
np.random.randint(1,4,(4,4))

array([[1, 2, 1, 2],
       [2, 2, 3, 3],
       [3, 2, 3, 2],
       [3, 2, 2, 3]])

In [87]:
#creating 3D array 

In [88]:
np.random.randint(1,5,(3,3,3))

array([[[3, 2, 1],
        [3, 3, 2],
        [2, 1, 4]],

       [[3, 4, 4],
        [1, 1, 4],
        [3, 4, 4]],

       [[1, 4, 2],
        [1, 3, 1],
        [3, 2, 2]]])

In [89]:
np.random.rand(3)

array([0.59538786, 0.6039967 , 0.95000904])

In [90]:
np.random.rand(3,3)

array([[0.89057772, 0.3405583 , 0.53784889],
       [0.76105224, 0.39595751, 0.86386742],
       [0.14769349, 0.39008758, 0.40018469]])

In [91]:
np.random.randn(3,3)#returns samples of standard normal distribution

array([[ 1.73177598, -0.56552563, -0.65860025],
       [-0.58671626,  1.46086105,  0.78603337],
       [ 2.75897893, -2.04405455,  0.51403927]])